version: "3.6"

services:
  mailreader:
    build:
      context: .
    volumes:
      - ./app:/app
      - ./conf:/conf
      - ./maildir:/maildir
      - ./conf/afew/:/home/imapuser/.config/afew/
      - ./conf/.bogofilter/:/home/imapuser/.bogofilter/
    environment:
      - NOTMUCH_CONFIG=/conf/.notmuch-config
      - MAILDIR=/maildir
    ports:
      - "8745:8745"
      - "8080:8080"
    command: python3 account-sync.py
    #links:
    #  - "davmail:mail"
    #depends_on:
    #  - "davmail"
    #environment:
    #  XDG_CONFIG_HOME: /conf/config.json

  #davmail:
  #  image: connectical/davmail
  #  ports:
  #    - "1025:1025"
  #    - "1389:1389"
  #    - "1110:1110"
  #    - "1143:1143"
  #    - "1080:1080"
